name: Set Unity bundle version
inputs:
  file:
    description: path to ProjectSettings/ProjectSettings.asset
    required: false
    default: ProjectSettings/ProjectSettings.asset
  version:
    description: version in SemVer format
    required: true
  regex:
    description: ECMAScript Regular Expression to parse the version string for verification
    required: false
    default: "^(?<major>0|[1-9]\\d*)\\.(?<minor>0|[1-9]\\d*)(\\.(?<patch>0|[1-9]\\d*))?(?:-(?<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
outputs:
  version:
    description: version set to inputs.file
    value: ${{ steps.set.outputs.version }}
runs:
  using: composite
  steps:
  - id: set
    name: Set Unity bundle version to ${{ inputs.file }}
    shell: bash
    run: |-
      version=$(unity-bundle-version set --version '${{ inputs.version }}' --regex '${{ inputs.regex }}' '${{ inputs.file }}')
      echo ${version}
      echo "version=${version}" >> $GITHUB_OUTPUT
