name: Get Unity bundle version
inputs:
  file:
    description: path to ProjectSettings/ProjectSettings.asset
    required: false
    default: ProjectSettings/ProjectSettings.asset
  regex:
    description: ECMAScript Regular Expression to parse the version string for verification
    required: false
    default: "^(?<major>0|[1-9]\\d*)\\.(?<minor>0|[1-9]\\d*)(\\.(?<patch>0|[1-9]\\d*))?(?:-(?<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
outputs:
  version:
    description: version retrieved from inputs.file
    value: ${{ steps.get.outputs.version }}
runs:
  using: composite
  steps:
  - id: get
    name: Get Unity bundle version from ${{ inputs.file }}
    shell: bash
    run: |-
      unity-bundle-version get --regex '${{ inputs.regex }}' '${{ inputs.file }}'
      echo "version=$(unity-bundle-version get --regex '${{ inputs.regex }}' '${{ inputs.file }}')" >> $GITHUB_OUTPUT
  - shell: bash
    run: |-
      echo ${{ steps.get.outputs.version }}
