name: Build Test

on:
  push:
    branches-ignore:
      - main

## Does the same stuff as release
## EXCEPT publishing the artifacts

jobs:
  buildtest:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Create package
        id: pack
        run: |
          npm pack
          echo "package=$(ls *.tgz)" >> $GITHUB_OUTPUT
      - name: Show package
        run: |
          ls ${{ steps.pack.outputs.package }}
          tar tvf ${{ steps.pack.outputs.package }}
