name: Test Set

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Set
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: npm install


      # simple test on fixed test data
      - name: Test on simple format
        run: |
          node . set --version '4.5.6'    testdata/simple/ProjectSettings.asset
          echo "version=$(node . get    testdata/simple/ProjectSettings.asset)" >> $GITHUB_OUTPUT
        id: simple
      - name: Print results
        run: echo ${{ steps.simple.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.simple.outputs.version }}" == "4.5.6" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # simple test with custom regex on fixed test data
      - name: Test on simple format with custom regex
        run: |
          node . set --version '7.8.9'  --regex '^(?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+)$'    testdata/simple/ProjectSettings.asset
          echo "version=$(node . get    testdata/simple/ProjectSettings.asset)" >> $GITHUB_OUTPUT
        id: custom
      - name: Print results
        run: echo ${{ steps.custom.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.custom.outputs.version }}" == "7.8.9" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # prerelease test on fixed test data
      - name: Test on prerelease format
        run: |
          node . set --version '4.5.6-alpha.1'    testdata/prerelease/ProjectSettings.asset
          echo "version=$(node . get    testdata/prerelease/ProjectSettings.asset)" >> $GITHUB_OUTPUT
        id: prerelease
      - name: Print results
        run: echo ${{ steps.prerelease.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.prerelease.outputs.version }}" == "4.5.6-alpha.1" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # buildmeta test on fixed test data
      - name: Test on buildmetadata format
        run: |
          node . set --version '4.5.6+baz.56'    testdata/buildmeta/ProjectSettings.asset
          echo "version=$(node . get    testdata/buildmeta/ProjectSettings.asset)" >> $GITHUB_OUTPUT
        id: buildmeta
      - name: Print results
        run: echo ${{ steps.buildmeta.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.buildmeta.outputs.version }}" == "4.5.6+baz.56" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # complex test on fixed test data
      - name: Test on complex format
        run: |
          node . set --version '4.5.6-alpha.1+baz.56'     testdata/complex/ProjectSettings.asset
          echo "version=$(node . get    testdata/complex/ProjectSettings.asset)" >> $GITHUB_OUTPUT
        id: complex
      - name: Print results
        run: echo ${{ steps.complex.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.complex.outputs.version }}" == "4.5.6-alpha.1+baz.56" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

  test-action:
    runs-on: ubuntu-latest
    name: Test Set Action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/install


      # simple test on fixed test data
      - name: Test on simple format
        uses: ./.github/actions/set-version
        with:
          version: '4.5.6'
          file: testdata/simple/ProjectSettings.asset
        id: simple
      - name: Print results
        run: echo ${{ steps.simple.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.simple.outputs.version }}" == "4.5.6" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # simple test with custom regex on fixed test data
      - name: Test on simple format with custom regex
        uses: ./.github/actions/set-version
        with:
          version: '7.8.9'
          regex: '^(?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+)$'
          file: testdata/simple/ProjectSettings.asset
        id: custom
      - name: Print results
        run: echo ${{ steps.custom.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.custom.outputs.version }}" == "7.8.9" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # prerelease test on fixed test data
      - name: Test on prerelease format
        uses: ./.github/actions/set-version
        with:
          version: '4.5.6-alpha.1'
          file: testdata/prerelease/ProjectSettings.asset
        id: prerelease
      - name: Print results
        run: echo ${{ steps.prerelease.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.prerelease.outputs.version }}" == "4.5.6-alpha.1" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # buildmeta test on fixed test data
      - name: Test on buildmetadata format
        uses: ./.github/actions/set-version
        with:
          version: '4.5.6+baz.56'
          file: testdata/buildmeta/ProjectSettings.asset
        id: buildmeta
      - name: Print results
        run: echo ${{ steps.buildmeta.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.buildmeta.outputs.version }}" == "4.5.6+baz.56" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi

      # complex test on fixed test data
      - name: Test on complex format
        uses: ./.github/actions/set-version
        with:
          version: '4.5.6-alpha.1+baz.56'
          file: testdata/complex/ProjectSettings.asset
        id: complex
      - name: Print results
        run: echo ${{ steps.complex.outputs.version }}
      - name: Verify results
        run: |
          if [ "${{ steps.complex.outputs.version }}" == "4.5.6-alpha.1+baz.56" ]; then
            echo "Version matches"
          else
            echo "Version mismatch"
            exit -1
          fi
